repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.90.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_validate
      args:
        - --args=-json
        - --args=-no-color
        - --tf-init-args=-upgrade
        - --tf-init-args=-lockfile=readonly
        - --hook-config=--parallelism-ci-cpu-cores=1