name: TFlint on PR

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  tflint:
    name: TFlint linting
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
    - uses: actions/checkout@v4
      name: Checkout source code

    - uses: terraform-linters/setup-tflint@v3
      name: Setup TFLint
      with:
        tflint_wrapper: true
        tflint_version: latest

    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Run TFLint
      id: tflint
      run: tflint -f compact
